# Лабораторна робота 2
#### Пушкар Максим, Варіант 11

In [343]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (10, 6)

from sklearn.model_selection import train_test_split

In [344]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

### Робота з даними

URL: https://archive.ics.uci.edu/ml/datasets/Heart+Disease

Данi: processed.clivelend.data, heart-disease.names

Вiдгук: Остання колонка

Факторна змiнна: Колонка 2

In [345]:
data = pd.read_csv("processed.cleveland.data",
                 names=["age", "sex", "cp", "trestbps", "chol", 
                        "fbs", "restecg", "thalach", "exang", "oldpeak", 
                        "slope", "ca", "thal", "num"])
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [346]:
data.isna().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
num         False
dtype: bool

Якщо уважно подивитися на данні, то можна побачити, що вони насправді мають пропуски в колонках "thal", "ca" у форматі "?", можливо в деяких інших також.

In [347]:
data[87:88]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
87,53.0,0.0,3.0,128.0,216.0,0.0,2.0,115.0,0.0,0.0,1.0,0.0,?,0

In [348]:
data.shape

(303, 14)

In [349]:
# виправляємо це
df = data[data != "?"]
df = df.dropna()

df.shape

(297, 14)

Насправді, в цих даних є ще одна проблему, яку зовсім не легко побачити:

In [350]:
print(df["thal"][0])
print(type(df["thal"][0]))

6.0
<class 'str'>

Тобто у стовпчиках, звідки ми видаляли знаки запитання, python вважає дані в них рядками, а не числами. 
А більшість наступних функцій бачать рядки, не можуть їх інтерплітувати, але нічого не кажуть, а викидають всі стовпчики з цими даними. Тому цю помилку я знайшов наприкінці всієї роботи, коли дерево відмовляло генеруватися.

In [351]:
df["thal"] = df["thal"].astype(float)
df["ca"] = df["ca"].astype(float)

print(df["thal"][0])
print(type(df["thal"][0]))

6.0
<class 'numpy.float64'>

In [352]:
y = df["num"]
X = df.drop(columns=["num"])

### Класифiкатори

In [353]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=27052022)

In [354]:
# https://scikit-learn.org/stable/modules/naive_bayes.html
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)

print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
#print("Неправильно класифікованих із %d точок : %d" % (X_test.shape[0], (y_test != y_pred).sum()))

Точність моделі на тренувальній вибірці = 0.6413502109704642
Точність моделі на тестовій вибірці= 0.55

In [355]:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(6)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

model = KNeighborsClassifier(10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

model = KNeighborsClassifier(15)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 0.569620253164557
Точність моделі на тестовій вибірці= 0.55

Точність моделі на тренувальній вибірці = 0.5485232067510548
Точність моделі на тестовій вибірці= 0.6

Точність моделі на тренувальній вибірці = 0.5274261603375527
Точність моделі на тестовій вибірці= 0.65

Бачимо, що вийшло незначно покращити якість моделі, але цей результат не можна назвати хорошим. 

Також бачимо, що ця модель не має великого потенціалу, бо на тренувальній вибірці вдалося отримати точність близько 0.55

In [356]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 0.6497890295358649
Точність моделі на тестовій вибірці= 0.6333333333333333

C:\Users\MAXIM\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [357]:
from sklearn.svm import SVC

model = SVC(kernel='poly')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

model = SVC(kernel='rbf')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 0.5189873417721519
Точність моделі на тестовій вибірці= 0.6166666666666667

Точність моделі на тренувальній вибірці = 0.7046413502109705
Точність моделі на тестовій вибірці= 0.5833333333333334

Точність моделі на тренувальній вибірці = 0.5189873417721519
Точність моделі на тестовій вибірці= 0.6166666666666667

Бачимо, що за допомогою цих моделей не вдається покращити результат. Вони також не мають набагато більшого потенціалу на тренувальній вибірці.

In [358]:
import xgboost
model = xgboost.XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 1.0
Точність моделі на тестовій вибірці= 0.6166666666666667

In [359]:
model = xgboost.XGBClassifier(max_depth=4)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 1.0
Точність моделі на тестовій вибірці= 0.6

In [360]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 1.0
Точність моделі на тестовій вибірці= 0.6166666666666667

In [361]:
model = RandomForestClassifier(max_depth=8)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 0.9957805907172996
Точність моделі на тестовій вибірці= 0.6333333333333333

Дерева дають точність на тренувальній вибірці близько 1 для достатньо великої глибини, але все ж таки не можуть значно покращити результат та перескочити через позначку 0.65 в точності на тестовій вибірці, як і всі інші варіанти до цього. Звичайно, 65% це не так погано для 4х вариіантів класифікації, але звичайно хотілося-б більшого.

### Факторні дані

За умовою варіанту факторною змiнною потрібно обрати колонку "sex", тобто поділити на male та female.

In [374]:
df_1 = df.copy()
df_1.insert(0, column="male", value=df["sex"])
df_1.insert(0, column="female", value=(-df_1["sex"]+1))
df_1

,female,male,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,0.0,1.0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,0.0,1.0,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,0.0,1.0,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,0.0,1.0,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,1.0,0.0,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,1.0,0.0,57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
298,0.0,1.0,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,0.0,1.0,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,0.0,1.0,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,1.0,0.0,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1

In [375]:
df_1.drop(columns=["sex"])

,female,male,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,0.0,1.0,63.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,0.0,1.0,67.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,0.0,1.0,67.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,0.0,1.0,37.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,1.0,0.0,41.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,1.0,0.0,57.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
298,0.0,1.0,45.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,0.0,1.0,68.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,0.0,1.0,57.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,1.0,0.0,57.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1

Зробимо тепер тут декілька класифікаторів:

In [379]:
y = df_1["num"]
X = df_1.drop(columns=["num"])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=27052022)


model = RandomForestClassifier(max_depth=8)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()


model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()


model = KNeighborsClassifier(15)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_1 = model.predict(X_train)
print(f"Точність моделі на тренувальній вибірці = {accuracy_score(y_train, y_pred_1)}")
print(f"Точність моделі на тестовій вибірці= {accuracy_score(y_test, y_pred)}")
print()

Точність моделі на тренувальній вибірці = 0.9957805907172996
Точність моделі на тестовій вибірці= 0.6333333333333333

Точність моделі на тренувальній вибірці = 0.6962025316455697
Точність моделі на тестовій вибірці= 0.5833333333333334

Точність моделі на тренувальній вибірці = 0.5274261603375527
Точність моделі на тестовій вибірці= 0.65

Ми не змогли таки переступити через поріг 65%, але можна бачити, що точність трьох моделей вище покращилася, хоча й незначно.

### Висновок

Отже, ми побудували багато варіантів класифікації. 

Найкращими виявилися LogisticRegression та RandomForestClassifier(max_depth=8), але в нашому випадку всі значення точності коливалися приблизно від 0.5 до 0.65, тому наврядчи ці класифікатори залишаться найкращими й для іншої випадкової тестової вибірки. Багато класифікаторів не показували гарний результат навіть на тренувальній вибірці, не говорячи вже про тестову.

Можемо зробити висновок, що для нашої задачі прогнозу сердцевих захворювань складно знайти дуже хорошу модель, але певного прогресу досягти вдається, та приблизно с 65% ймовірністю можна вказати не лише відсутність чи присутність захворювання, а й ступінь його серйозності.